services:
  evrinoma.nomenclature.constraint.property.item.vendor:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Item\Vendor
  evrinoma.nomenclature.constraint.property.item.active:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Item\Active
  evrinoma.nomenclature.constraint.property.item.Standartd:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Item\Standartd
  evrinoma.nomenclature.constraint.property.item.postition:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Item\Position
