services:
  evrinoma.nomenclature.constraint.property.item.description:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Item\Description
  evrinoma.nomenclature.constraint.property.item.brief:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Item\Brief
  evrinoma.nomenclature.constraint.property.item.active:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Item\Active
  evrinoma.nomenclature.constraint.property.item.image:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Item\Image
  evrinoma.nomenclature.constraint.property.item.item:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Item\Position
