services:
  evrinoma.nomenclature.constraint.property.nomenclature.description:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Nomenclature\Description

  evrinoma.nomenclature.constraint.property.nomenclature.title:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Nomenclature\Title

  evrinoma.nomenclature.constraint.property.nomenclature.active:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Nomenclature\Active

  evrinoma.nomenclature.constraint.property.nomenclature.position:
    class: Evrinoma\NomenclatureBundle\Constraint\Property\Nomenclature\Position


